### ISSUE TITLE
Add Matomo analytics to search

### ISSUE THREAD

**Issue by yannic-bruegger** [lucascranach/cranach-search#112]

**Comment by yannic-bruegger** [comment]
![Image](https://github.com/lucascranach/cranach-search/assets/36576062/7b0d5b41-35df-4f81-ae9a-87f2db678083)

**Comment by yannic-bruegger** [comment]
Ich habe auch im externen Bereich die neue Version deployed? War das falsch @markusalterauge ? :o

**Comment by markusalterauge** [comment]
Extern ist auch fein, finde allerdings den Matomo Code nur im Internen.

**Comment by yannic-bruegger** [comment]
Das sollte ich gefixt haben, oder? :)
Dann kann das Issue geschlossen werden
