### ISSUE TITLE
Falsche Sprache im Lang Attribut

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cranach-search#116]
view-source:https://lucascranach.org/de/search/

Dadurch springt der Übersetzer an. Das müssten wir ändern :)

**Comment by yannic-bruegger** [comment]
Habe es einfach statisch auf Deutsch geändert. Reicht dir das? :) Würde es dann schnell in den nächsten Release mit reinnehmen.

**Comment by yannic-bruegger** [comment]
Aus versehen geschlosse, ich mache es mal wieder auf, bis es auch produktiv gefixt ist. :)
