### ISSUE TITLE
Bei Übersichtsdarstellung Gemälde mit Kacheln falscher Wert zu Material / Technik online angezeigt 

### ISSUE THREAD

**Issue by CranacharchivGunnar** [lucascranach/cranach-search#124]
### URL of the buggy page?

https://lucascranach.org/de

### Contact Details

gunnar.heydenreich@th-koeln.de

### What happened?

Online in der Übersichtsdarstellung der Gemälde mit den großen Kacheln wird unter den Abbildungen des ersten Objektes im cda angezeigt:
Kreuzigung Christi, sog. "Schottenkreuzigung", 1501
**Malerei,**
Kunsthistorisches Museum, Wien

Hingegen wird in der Übersichtsdarstellung mit den Listen für das gleiche Werk angezeigt:
Kreuzigung Christi, sog. "Schottenkreuzigung", 1501
**Malerei auf Lindenholz (Tilia sp.)**
Lucas Cranach der Ältere
Maße Bildträger: 58,4 (oben) - 58,1 (unten) x 45,1(links) - 45.8 (rechts) x 2,5 - 2,6 cm
Kunsthistorisches Museum, Wien

D.h. der Eintrag zu Material/Technik "Malerei," wird aktuell offenbar für die Übersichtsdarstellung mit den großen Kacheln aus dem Thesaurus gezogen und der Eintrag "Malerei auf Lindenholz (Tilia sp.) für die anderen Listenübersichtsdarstellung aus dem Feldeintrag zu "Material/Technik".
Bitte darum, vorerst (wie wir das bisher online hatten) bei allen Ansichten (Kacheln und Listen) den Eintrag aus dem Feldeintrag zu "Material/Technik" anzuzeigen, d.h.
in diesem Fall wäre das korrekt "Malerei auf Lindenholz (Tilia sp.)"
(Ich glaube, wir hatten da auch eine Abkürzungsregel hinterlegt "Anzeige des Eintrags bis zum ersten Komma" oder so ähnlich...)

Perspektivisch werden wir die Thesauruseinträge soweit pflegen, dass ggf. diese auch für die Übersichtsdarstellung genutzt werden können, aber aktuell ist die wechselnde Anzeige irritierend...
Danke!

**Comment by yannic-bruegger** [comment]
Ist das so, wie ihr es euch vorgestellt habt  @CranacharchivGunnar? Soll ich die Version erstmal intern veröffentlichen?


![Image](https://github.com/lucascranach/cranach-search/assets/36576062/3cd191f1-044f-4396-9410-c5a4eb9622cc)

**Comment by CranacharchivGunnar** [comment]
Ja, sieht gut aus. Kannst Du gern direkt freischalten.

**Comment by yannic-bruegger** [comment]
Ist auf dem Weg :)

**Comment by yannic-bruegger** [comment]
Mit STRG+F5 ist es jetzt veröffentlicht unter: https://lucascranach.org/de/search

Ohne Cache-Reload dann in Kürze :) Ich schließe das Issue damit ab. Danke dir Gunnar!

**Comment by CranacharchivGunnar** [comment]
Wunderbar, bin dankbar, dass die Zeile nun wieder korrekt erscheint und wünsche einen schönen Vorfrühlingsabend!!
